name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server
      run: |
        echo "Running SSH command..."
        ssh -o StrictHostKeyChecking=no ditya@youre-chronically.online << 'EOF'
          pkill screen
          screen
          cd /home/ditya/APL-TA
          git pull origin master
          node ./app.js
        EOF
